name: 'Careflow Validation'
description: Validate cases using this action
author: Awell Health

# Define your inputs here.
inputs:
  filename:
    description: 'The link to the .yaml file with the cases with instructions'
    required: true
    default: careflow-validation.yaml
  api_key:
    description: 'The Awell API key to use for authentication.'
    required: true
  awell_environment:
    description: 'The endpoint to use for the GraphQL API.'
    required: true
    default: development
  careflow_id:
    description: 'The ID of the careflow to validate.'
    required: true
  timeout_ms:
    description: 'Timeout to fail in ms'
    default: '60000'

# Define your outputs here.
outputs:
  results:
    description: 'The results of the test cases'

runs:
  using: node20
  main: 'dist/index.js'
