name: Continuous Integration

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version-file: .node-version
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

      - name: Bundle
        id: npm-bundle
        run: npm run bundle

      - name: Commit and push updated version
        id: bump_version
        run: |
          echo "$(git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'## %H%n%an <%ae>%n%ad%n%s%n%b%n')" > release_body.md
          yarn version --patch
          new_version=$(cat package.json | jq -r '.version')
          git config --global user.name "Awell CI"
          git config --global user.email "ci@awellhealth.com"
          git add package.json
          git commit -m "ci: bump version to $new_version [skip ci]" && git push
          git tag -a $new_version -m "ci: bump version to $new_version" && git push origin $new_version
          echo "new_version=$new_version" >> "$GITHUB_OUTPUT"

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.CONTENTS_AND_WORKFLOWS_TOKEN }}
          TAG_NAME: ${{ steps.bump_version.outputs.new_version }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body_path: release_body.md
          draft: false
          prerelease: false

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      # TODO: Add support for bypassing API for local testing
      # - name: Test Local Action
      #   id: test-action
      #   uses: ./
      #   with:
      #     api_key: test
      #     careflow_id:

      # - name: Print Output
      #   id: output
      #   run: echo "${{ steps.test-action.outputs.time }}"
